image:
  name: gaiescicd

stages:
  - DEV1
  - SIT1
  - SIT2

cache:
  key: demo
  untracked: true
  policy: pull-push

prep:
  stage: DEV1
  script:
    - sudo pip install boto boto3 netaddr passlib
    - export AWS_PROFILE=mgmt
    - pwd
    - export PATH=$PATH:/usr/local/bin
    - ansible --version
    - ansible-playbook /home/gitlab-runner/builds/G1RPJgRJ/0/root/georgiaies_main/ansible_cft_s3_upload.yml
  artifacts:
    untracked: true
    when: always
  allow_failure: true
  when: manual


DeployDev:
  stage: DEV1
  script:
    - sudo pip install boto boto3 netaddr passlib
    - export AWS_PROFILE=mgmt
    - pwd
    - export PATH=$PATH:/usr/local/bin
    - ansible --version
    - ansible-playbook /home/gitlab-runner/builds/G1RPJgRJ/0/root/georgiaies_main/ansible_app_deploy.yml
  artifacts:
    untracked: true
    when: always
  allow_failure: true
  when: manual

SIT1:
  stage: SIT1
  dependencies:
    - DeployDev
  variables:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  script:
    - sudo pip install boto boto3 netaddr passlib
    - export AWS_PROFILE=mgmt
    - pwd
    - export PATH=$PATH:/usr/local/bin
    - ansible --version
    - ansible-playbook /home/gitlab-runner/gaies-playbook/test-sg-play.yml
  allow_failure: true
  when: manual 