AWSTemplateFormatVersion: 2010-09-09

################################PARAMETERS######################################

Parameters:
  S3Location:
    Description: Your S3 location to store cloudformation template
    Type: String
    Default: "https://gaies-mgmt-s3-bucket.s3.amazonaws.com/"
    MinLength: 1
  Env:
    Description: Select a Environment
    Type: String
    AllowedValues:
      - prod
      - pre-prod
      - TRN
      - MM
      - UAT
      - DEV1
      - DEV2
      - SIT1
      - SIT2

############################## CONDITIONS #####################################

Conditions:
  prodVPC:
    !Equals [!Ref Env, prod]
  NonprodVPC:
    !Or [!Equals [!Ref Env, pre-prod], !Equals [!Ref Env, UAT], !Equals [!Ref Env, TRN], !Equals [!Ref Env, MM]]
  BuildVPC:
    !Or [!Equals [!Ref Env, DEV1], !Equals [!Ref Env, DEV2], !Equals [!Ref Env, SIT1], !Equals [!Ref Env, SIT2]]

######################################RESOURCES################################

Resources:

###############################SECURITY GROUPS#####################################

  ###############################SECURITY GROUPS#####################################

  AppSGStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ["",[!Ref S3Location,"SG_Templates/App_SG_Template.yaml"]]
      TimeoutInMinutes: '5'
      Parameters: 
        VPCStackName: !If [prodVPC, ProdVPCStack, !If [NonprodVPC, NonprodVPCStack, BuildVPCStack]]
        Env: !Ref Env


###############################EC2 stacks#####################################

  ProdWPEC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ["",[!Ref S3Location,"EC2_Template/Generic_EC2_Template.yaml"]]
      TimeoutInMinutes: '5'
      Parameters:
        VPCStackName: 'ProdVPCStack'
        EnvType: !Ref Env 
        InstanceCount: '2'
        InstanceType: 'WP'
        SubnetNameprefix: 'App'
        AMI: 'ami-9be6f38c' # need to parameterize
        InstanceSecurityGroup: Fn::GetAtt: 
          - AppSGStack
          - Outputs
          - !Join ["-", [!Ref Env,CP-SG]]
        InstanceType: 't3.medium' # need to parameterize
    
  
