AWSTemplateFormatVersion: 2010-09-09

################################PARAMETERS######################################

Parameters:
  S3Location:
    Description: Your S3 location to store cloudformation template
    Type: String
    Default: "https://gaies-mgmt-s3-bucket.s3.amazonaws.com/"
    MinLength: 1
  Env:
    Description: Select a Environment
    Type: String
    AllowedValues:
      - prod
      - pre-prod
      - TRN
      - MM
      - UAT
      - DEV1
      - DEV2
      - SIT1
      - SIT2
  VPCStackName: 
    Description: VPC Stack to which it should be associated to 
    Type: String

############################## CONDITIONS #####################################

######################################RESOURCES################################

Resources:

###############################SECURITY GROUPS#####################################

  ###############################SECURITY GROUPS#####################################

  AppSGStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ["",[!Ref S3Location,"SG_Templates/App_SG_Template.yaml"]]
      TimeoutInMinutes: '5'
      Parameters: 
        VPCStackName: !Ref VPCStackName
        Env: !Ref Env


###############################EC2 stacks#####################################

  WPEC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Join ["",[!Ref S3Location,"EC2_Templates/Generic_EC2_Template.yaml"]]
      TimeoutInMinutes: '5'
      Parameters:
        VPCStackName: !Ref VPCStackName
        EnvType: !Ref Env 
        InstanceCount: '1'
        AppModule: 'WP'
        InstanceHasFTI: false # need to parameterize
        SubnetNameprefix: !Join ["",!Ref VPCStackName,'App']]
        AMI: 'ami-9be6f38c' # need to parameterize
        InstanceSecurityGroup: !GetAtt 
          - AppSGStack
          - Outputs.WorkerPortalSG
        InstanceType: 't3.medium' # need to parameterize
  
  # WPEC2Stack:
  # Type: AWS::CloudFormation::Stack
  # Properties:
  #   TemplateURL: !Join ["",[!Ref S3Location,"EC2_Templates/Generic_EC2_Template.yaml"]]
  #   TimeoutInMinutes: '5'
  #   Parameters:
  #     VPCStackName: !Ref VPCStackName
  #     EnvType: !Ref Env 
  #     InstanceCount: '1'
  #     AppModule: 'WP'
  #     InstanceHasFTI: false # need to parameterize
  #     SubnetNameprefix: !Join ["",!Ref VPCStackName,'App']]
  #     AMI: 'ami-9be6f38c' # need to parameterize
  #     InstanceSecurityGroup: !GetAtt 
  #       - AppSGStack
  #       - Outputs.WorkerPortalSG
  #     InstanceType: 't3.medium' # need to parameterize
    
  
