AWSTemplateFormatVersion: 2010-09-09

################################METADATA########################################

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: VPC
        Parameters:
          - VPCName
          - CidrBlock
          - InternalSubnetAZ1CIDR
          - InternalSubnetAZ2CIDR
      -
        Label:
          default: EC2
        Parameters:
          - EC2Stack
          - AMI
          - InstanceType
          - InstanceCount
      -
        Label:
          default: S3
        Parameters:
          - S3Location

    ParameterLabels:
      VPCName:
        default: Name of the VPC
      CidrBlock:
        default: The IP address range that can be used to SSH to the EC2 instances
      InternalSubnetAZ1CIDR:
        default: CIDR IP for Internal Subnet A. 
      InternalSubnetAZ2CIDR:
        default: CIDR IP for Internal Subnet B.
      EC2Stack:
        default: The EC2 stack to install
      AMI:
        default: AMI for the instance
      InstanceType:
        default: Instance Type for the severs
      InstanceCount:
        default: Number of instances to create for the server
      S3Location:
        default: Your S3 location to store cloudformation template

################################PARAMETERS######################################

Parameters:
  S3Location: 
    #Description: Your S3 location to store cloudformation template
    Type: String
    Default: "https://anil-cft-bucket.s3.amazonaws.com"
    MinLength: 1

  EnvType:
    Type: String
    Default: non-prod
    AllowedValues:
      - prod
      - non-prod

  VPCName:
    Type: String
    #Description: Name your VPC

  CidrBlock:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    #Description: The IP address range that can be used to SSH to the EC2 instances
    ConstraintDescription: Must be a valid IP CIDR range orm x.x.x.x/x

  InternalSubnetAZ1CIDR:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    #Description: CIDR IP for Subnet A
    ConstraintDescription: Must be a valid IP CIDR range orm x.x.x.x/x

  InternalSubnetAZ2CIDR:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    #Description: CIDR IP for Subnet B
    ConstraintDescription: Must be a valid IP CIDR range orm x.x.x.x/x

  # EC2Stack:
  #   Type: String
  #   #Description: The EC2 stack to install
  #   AllowedValues:
  #     - BastionHost
  #     - Ansible
  #     - Trend
  #     - Centrify
  #     - SecurityTenable
  #     - WSUS
  #     - AD
  #     - RTC
  #     - UrbanCode
  #     - Remedy

  InstanceCount:
    Type: Number
    MinValue: 1
    MaxValue: 6
    Default: 2
    #Description: Number of instances to create for the server
  
  AMI: 
    Type: String
    #Description: AMI for the instance

  InstanceType:
    Type: String
    AllowedValues:
      - t3.medium
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.8xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.8xlarge
      - r5.large
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.8xlarge
      - r5.12xlarge


############################## CONDITIONS #####################################

# Conditions:
#   cBastionHost: !Equals [!Ref EC2Stack, BastionHost]
#   cAnsible: !Equals [!Ref EC2Stack, Ansible]
#   cTrend: !Equals [!Ref EC2Stack, Trend]
#   cCentrify: !Equals [!Ref EC2Stack, Centrify]
#   cSecurityTenable: !Equals [!Ref EC2Stack, SecurityTenable]
#   cWSUS: !Equals [!Ref EC2Stack, WSUS]
#   cAD: !Equals [!Ref EC2Stack, AD]
#   cRTC: !Equals [!Ref EC2Stack, RTC]
#   cUrbanCode: !Equals [!Ref EC2Stack, UrbanCode]
#   cRemedy: !Equals [!Ref EC2Stack, Remedy]


######################################RESOURCES################################

Resources:

#########################################VPC####################################

  ManagementVPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://anil-cft-bucket.s3.amazonaws.com/VPC_Templates/Management_Network_Template.yaml
      TimeoutInMinutes: '5'
      Parameters:
        VPCName: !Ref VPCName
        CidrBlock: !Ref CidrBlock
        InternalASubnetCIDR: !Ref InternalSubnetAZ1CIDR
        InternalBSubnetCIDR: !Ref InternalSubnetAZ2CIDR


###############################SECURITY GROUPS#####################################

  ManagementSGStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://anil-cft-bucket.s3.amazonaws.com/SG_Templates/Management_SG_Template.yaml
      TimeoutInMinutes: '5'
      Parameters:
        EnvType: !Ref EnvType
###############################IAM Roles#####################################


###############################EC2 stacks#####################################

  BastionHostEC2Stack:
    Type: AWS::CloudFormation::Stack
    # Condition: cBastionHost
    Properties:
      TemplateURL: https://anil-cft-bucket.s3.amazonaws.com/EC2_Templates/Master_EC2_Template.yaml
      TimeoutInMinutes: '5'
      Parameters:
        VPCStackName: 'ManagementVPCStack'
        EnvType: 'PRD' 
        InstanceCount: !Ref InstanceCount
        InstanceNamePrefix: 'gaiesmgmtbastionhost'
        AMI: !Ref AMI
        InstanceSecurityGroup: !ImportValue
              'Fn::Sub': 'ManagementSGStack-BastionHost'
        InstanceType: !Ref InstanceType

  AnsibleEC2Stack:
    Type: AWS::CloudFormation::Stack
    # Condition: cAnsible
    Properties:
      TemplateURL: https://anil-cft-bucket.s3.amazonaws.com/EC2_Templates/Master_EC2_Template.yaml
      TimeoutInMinutes: '5'
      Parameters:
        VPCStackName: 'ManagementVPCStack'
        EnvType: 'PRD' 
        InstanceCount: !Ref InstanceCount
        InstanceNamePrefix: 'gaiesmgmtansible'
        AMI: !Ref AMI
        InstanceSecurityGroup: !ImportValue
              'Fn::Sub': 'ManagementSGStack-Ansible'
        InstanceType: !Ref InstanceType 

  TrendEC2Stack:
    Type: AWS::CloudFormation::Stack
    # Condition: cTrend
    Properties:
      TemplateURL: https://anil-cft-bucket.s3.amazonaws.com/EC2_Templates/Master_EC2_Template.yaml
      TimeoutInMinutes: '5'
      Parameters:
        VPCStackName: 'ManagementVPCStack'
        EnvType: 'PRD' 
        InstanceCount: !Ref InstanceCount
        InstanceNamePrefix: 'gaiesmgmttrend'
        AMI: !Ref AMI
        InstanceSecurityGroup: !ImportValue
              'Fn::Sub': 'ManagementSGStack-Trend'
        InstanceType: !Ref InstanceType     
  
  CentrifyEC2Stack:
    Type: AWS::CloudFormation::Stack
    # Condition: cCentrify
    Properties:
      TemplateURL: https://anil-cft-bucket.s3.amazonaws.com/EC2_Templates/Master_EC2_Template.yaml
      TimeoutInMinutes: '5'
      Parameters:
        VPCStackName: 'ManagementVPCStack'
        EnvType: 'PRD' 
        InstanceCount: !Ref InstanceCount
        InstanceNamePrefix: 'gaiesmgmtcentrify'
        AMI: !Ref AMI
        InstanceSecurityGroup: !ImportValue
              'Fn::Sub': 'ManagementSGStack-Centrify'
        InstanceType: !Ref InstanceType

  SecurityTenableEC2Stack:
    Type: AWS::CloudFormation::Stack
    # Condition: cSecurityTenable
    Properties:
      TemplateURL: https://anil-cft-bucket.s3.amazonaws.com/EC2_Templates/Master_EC2_Template.yaml
      TimeoutInMinutes: '5'
      Parameters:
        VPCStackName: 'ManagementVPCStack'
        EnvType: 'PRD' 
        InstanceCount: !Ref InstanceCount
        InstanceNamePrefix: 'gaiesmgmtsecuritytenable'
        AMI: !Ref AMI
        InstanceSecurityGroup: !ImportValue
              'Fn::Sub': 'ManagementSGStack-SecurityTenable'
        InstanceType: !Ref InstanceType

  WSUSEC2Stack:
    Type: AWS::CloudFormation::Stack
    # Condition: cWSUS
    Properties:
      TemplateURL: https://anil-cft-bucket.s3.amazonaws.com/EC2_Templates/Master_EC2_Template.yaml
      TimeoutInMinutes: '5'
      Parameters:
        VPCStackName: 'ManagementVPCStack'
        EnvType: 'PRD' 
        InstanceCount: !Ref InstanceCount
        InstanceNamePrefix: 'gaiesmgmtwsus'
        AMI: !Ref AMI
        InstanceSecurityGroup: !ImportValue
              'Fn::Sub': 'ManagementSGStack-WSUS'
        InstanceType: !Ref InstanceType

  ADEC2Stack:
    Type: AWS::CloudFormation::Stack
    # Condition: cAD
    Properties:
      TemplateURL: https://anil-cft-bucket.s3.amazonaws.com/EC2_Templates/Master_EC2_Template.yaml
      TimeoutInMinutes: '5'
      Parameters:
        VPCStackName: 'ManagementVPCStack'
        EnvType: 'PRD' 
        InstanceCount: !Ref InstanceCount
        InstanceNamePrefix: 'gaiesmgmtad'
        AMI: !Ref AMI
        InstanceSecurityGroup: !ImportValue
              'Fn::Sub': 'ManagementSGStack-AD'
        InstanceType: !Ref InstanceType

  RTCEC2Stack:
    Type: AWS::CloudFormation::Stack
    # Condition: cRTC
    Properties:
      TemplateURL: https://anil-cft-bucket.s3.amazonaws.com/EC2_Templates/Master_EC2_Template.yaml
      TimeoutInMinutes: '5'
      Parameters:
        VPCStackName: 'ManagementVPCStack'
        EnvType: 'PRD' 
        InstanceCount: !Ref InstanceCount
        InstanceNamePrefix: 'gaiesmgmtrtc'
        AMI: !Ref AMI
        InstanceSecurityGroup: !ImportValue
              'Fn::Sub': 'ManagementSGStack-RTC'
        InstanceType: !Ref InstanceType
  
  UrbanCodeEC2Stack:
    Type: AWS::CloudFormation::Stack
    # Condition: cUrbanCode
    Properties:
      TemplateURL: https://anil-cft-bucket.s3.amazonaws.com/EC2_Templates/Master_EC2_Template.yaml
      TimeoutInMinutes: '5'
      Parameters:
        VPCStackName: 'ManagementVPCStack'
        EnvType: 'PRD' 
        InstanceCount: !Ref InstanceCount
        InstanceNamePrefix: 'gaiesmgmtuc'
        AMI: !Ref AMI
        InstanceSecurityGroup: !ImportValue
              'Fn::Sub': 'ManagementSGStack-UrbanCode'
        InstanceType: !Ref InstanceType
  
  RemedyEC2Stack:
    Type: AWS::CloudFormation::Stack
    # Condition: cRemedy
    Properties:
      TemplateURL: https://anil-cft-bucket.s3.amazonaws.com/EC2_Templates/Master_EC2_Template.yaml
      TimeoutInMinutes: '5'
      Parameters:
        VPCStackName: 'ManagementVPCStack'
        EnvType: 'PRD' 
        InstanceCount: !Ref InstanceCount
        InstanceNamePrefix: 'gaiesmgmtremedy'
        AMI: !Ref AMI
        InstanceSecurityGroup: !ImportValue
              'Fn::Sub': 'ManagementSGStack-Remedy'
        InstanceType: !Ref InstanceType
