AWSTemplateFormatVersion: 2010-09-09

################################METADATA########################################

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Management_VPC"
        Parameters:
          - VPCName
          - CidrBlock
          - InternalSubnetAZ1CIDR
          - InternalSubnetAZ2CIDR

    ParameterLabels:
      VPCName:
        default: Name of the VPC
      CidrBlock:
        default: The IP address range that can be used to SSH to the EC2 instances
      InternalSubnetAZ1CIDR:
        default: CIDR IP for Internal Subnet A. 
      InternalSubnetAZ2CIDR:
        default: CIDR IP for Internal Subnet B.

################################PARAMETERS######################################

Parameters:

  VPCName:
    Type: String
    #Description: Name your VPC

  CidrBlock:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    #Description: The IP address range that can be used to SSH to the EC2 instances
    ConstraintDescription: Must be a valid IP CIDR range orm x.x.x.x/x

  InternalSubnetAZ1CIDR:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    #Description: CIDR IP for Subnet A
    ConstraintDescription: Must be a valid IP CIDR range orm x.x.x.x/x

  InternalSubnetAZ2CIDR:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
    #Description: CIDR IP for Subnet B
    ConstraintDescription: Must be a valid IP CIDR range orm x.x.x.x/x

############################## CONDITIONS #####################################

######################################RESOURCES################################

Resources:

#########################################VPC####################################

  ManagementVPCStack:
    Type: AWS::CloudFormation::Stack
    Condition: ManagementVPC
    Properties:
      TemplateURL: https://cftbuckettesting92839.s3.amazonaws.com/VPC_Templates/Management_Network_Template.yaml
      TimeoutInMinutes: '5'
      Parameters:
        VPCName: !Ref VPCName
        CidrBlock: !Ref CidrBlock
        InternalASubnetCIDR: !Ref InternalSubnetAZ1CIDR
        InternalBSubnetCIDR: !Ref InternalBSubnetAZ2CIDR


###############################SECURITY GROUPS#####################################

  ManagementSGStack:
    Type: AWS::CloudFormation::Stack
    Condition: ManagementSG
    Properties:
      TemplateURL: https://cftbuckettesting92839.s3.amazonaws.com/SG_Templates/Management_SG_Template.yaml
      TimeoutInMinutes: '5'
###############################IAM Roles#####################################


###############################EC2 stacks#####################################

  CentrifyEC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cftbuckettesting92839.s3.amazonaws.com/EC2_Templates/Master_EC2_Template.yaml
      TimeoutInMinutes: '5'
      Parameters:
        VPCStackName: 'ManagementVPCStack'
        EnvType: 'PRD' 
        InstanceCount: '2'
        InstanceNamePrefix: 'gaiesmgmtcentrify'
        AMI: 'ami-9be6f38c' # need to parameterize
        InstanceSecurityGroup: !ImportValue
              'Fn::Sub': 'ManagementSGStack-Centrify'
        InstanceType: 't3.medium' # need to parameterize
  
  UrbanCodeEC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cftbuckettesting92839.s3.amazonaws.com/EC2_Templates/Master_EC2_Template.yaml
      TimeoutInMinutes: '5'
      Parameters:
        VPCStackName: 'ManagementVPCStack'
        EnvType: 'PRD' 
        InstanceCount: '1' # need to parameterize
        InstanceNamePrefix: 'gaiesmgmtuc'
        AMI: 'ami-9be6f38c' # need to parameterize
        InstanceSecurityGroup: !ImportValue
              'Fn::Sub': 'ManagementSGStack-UrbanCode'
        InstanceType: 'c5.large' # need to parameterize
  
  RemedyEC2Stack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://cftbuckettesting92839.s3.amazonaws.com/EC2_Templates/Master_EC2_Template.yaml
      TimeoutInMinutes: '5'
      Parameters:
        VPCStackName: 'ManagementVPCStack'
        EnvType: 'PRD' 
        InstanceCount: '1' # need to parameterize
        InstanceNamePrefix: 'gaiesmgmtremedy'
        AMI: 'ami-9be6f38c' # need to parameterize
        InstanceSecurityGroup: !ImportValue
              'Fn::Sub': 'ManagementSGStack-Remedy'
        InstanceType: 'c5.large' # need to parameterize
