AWSTemplateFormatVersion: 2010-09-09

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Environment Type"
        Parameters:
          - Env
      -
        Label:
          default: "VPC Stack Name"
        Parameters:
          - VPCStackName

    ParameterLabels:
      VPCStackName:
        default: "Name of the VPC Stack in which these Security Groups belongs belong to."

      Env:
        default: Select a Environment Type

########################### PARAMETERS ##################################

Parameters:
  VPCStackName:
    #Description: Name of the VPC Stack in which these Security Groups belongs belong to.
    Type: String
    AllowedPattern: '[a-zA-Z][-a-zA-Z0-9]*$'

  Env:
    Type: String
    Default: dev
    AllowedValues: [dev, dev1, dev2, sit, sit1, prod, pre-prod, uat, trn]



########################### RESOURCES ##################################

Resources:

######################## CUSTOMER HTTP SERVER SECURITY GROUP #########################

  CustomerHTTPServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Customer HTTP Server in MarketPlace VPC. By default allows all outbound traffic.
      GroupName: !Join ["_", [!Ref Env, marketplace_customerhttpserver_sg]]
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: !ImportValue
              'Fn::Sub': '${VPCStackName}-VPC'
      Tags:
      - Key: Name
        Value: CustomerHTTPServer

########################## WORKER PORTAL SECURITY GROUP #############################

  WorkerPortalSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Worker Portal in MarketPlace VPC. By default allows all outbound traffic.
      GroupName: !Join ["_", [!Ref Env, marketplace_workerportal_sg]]
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: !ImportValue
              'Fn::Sub': '${VPCStackName}-VPC'
      Tags:
      - Key: Name
        Value: WorkerPortal

###################### CUSTOMER PORTAL SECURITY GROUP ##########################

  CustomerPortalSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Customer Portal in MarketPlace VPC. By default allows all outbound traffic.
      GroupName: !Join ["_", [!Ref Env, marketplace_customerportal_sg]]
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: !ImportValue
              'Fn::Sub': '${VPCStackName}-VPC'
      Tags:
      - Key: Name
        Value: CustomerPortal

########################## BATCH SECURITY GROUP ##############################

  BatchSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Batch in MarketPlace VPC. By default allows all outbound traffic.
      GroupName: !Join ["_", [!Ref Env, marketplace_batch_sg]]
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: !ImportValue
              'Fn::Sub': '${VPCStackName}-VPC'
      Tags:
      - Key: Name
        Value: Batch

##################### SFTP SECURITY GROUP ##########################

  SFTPSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for SFTP in MarketPlace VPC. By default allows all outbound traffic.
      GroupName: !Join ["_", [!Ref Env, marketplace_sftp_sg]]
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: !ImportValue
              'Fn::Sub': '${VPCStackName}-VPC'
      Tags:
      - Key: Name
        Value: SFTP

########################## ENTERPRISEDB SECURITY GROUP ##############################

  EnterpriseDBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for EnterpriseDB in MarketPlace VPC. By default allows all outbound traffic.
      GroupName: !Join ["_", [!Ref Env, marketplace_enterprisedb_sg]]
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: !ImportValue
              'Fn::Sub': '${VPCStackName}-VPC'
      Tags:
      - Key: Name
        Value: EnterpriseDB

########################### OUTPUTS ##################################

Outputs:
  StackName: 
    Description: get the nested stack names to be referenced in other templates. 
    Value: !Sub ${AWS::StackName}
    Export:
     Name: StackName
  CustomerHTTPServerSG:
    Description: Security Group Id for Customer HTTP Server in MarketPlace VPC
    Value: !Ref CustomerHTTPServerSG
    Export:
      Name: CP_HTTP

  WorkerPortalSG:
    Description: Security Group Id for Worker Portal in MarketPlace VPC
    Value: !Ref WorkerPortalSG
    Export:
      Name: WP

  CustomerPortalSG:
    Description: Security Group Id for Customer Portal in MarketPlace VPC
    Value: !Ref CustomerPortalSG
    Export:
      Name: CP

  BatchSG:
    Description: Security Group Id for Batch in MarketPlace VPC
    Value: !Ref BatchSG
    Export:
      Name: Batch

  SFTPSG:
    Description: Security Group Id for SFTP in MarketPlace VPC
    Value: !Ref SFTPSG
    Export:
      Name: SFTP

  EnterpriseDBSG:
    Description: Security Group Id for EnterpriseDB in MarketPlace VPC
    Value: !Ref EnterpriseDBSG
    Export:
      Name: EnterpriseDB
