AWSTemplateFormatVersion: 2010-09-09

Parameters:
  VpcId:
    Description: VPC ID that this stack will be launched in.
    Type: AWS::EC2::VPC::Id
    AllowedPattern: "[a-z0-9-]*"

  InstanceType:
    Description: Type of EC2 instance to launch for the server.
    Type: String
    Default: t2.medium
    ConstraintDescription: Must be a valid EC2 instance type.
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m4.16xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.12xlarge
      - m5.24xlarge

  SubnetId:
    Description: VPC Subnet that this stack will be launched in.
    Type: AWS::EC2::Subnet::Id
    AllowedPattern: "[a-z0-9-]*"

  KeyName:
    Description: Name of an existing EC2 keypair to enable SSH access to the instance(s).
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.

  InstanceTagName:
    Description: Instance Name tag that will be used to define the Name of the instance resource(s)
    Type: String
    Default: GAIES

  InstanceSecurityGroup:
    Description: Security Group for the EC2 instance
    Type: AWS::EC2::SecurityGroup::Id



Mappings:
  RegionMap:
    'us-east-1':
      AMI: 'ami-09d069a04349dc3cb'
    'us-west-1':
      AMI: 'ami-04bc3da8f14823e88'

Resources:
  PrdWPEC2:
    Description: Worker Portal (Production environment) EC2 Instance.
    Type: AWS::EC2::Instance
    Properties:
      NetworkInterfaces:
        - GroupSet:
            - !Ref InstanceSecurityGroup
          AssociatePublicIpAddress: 'true'
          DeviceIndex: '0'
          DeleteOnTermination: 'true'
          SubnetId: !Ref SubnetId
      ImageId: !FindInMap
        - RegionMap
        - !Ref 'AWS::Region'
        - AMI
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      Tags:
        - Key: Name
          Value: !Ref InstanceTagName
