AWSTemplateFormatVersion: 2010-09-09
Parameters:
  MgmtAccountId:
    Type: String
    Default: 588259907349
  MgmtAccountSharedServiceRole:
    Type: String
    Default: GAIESMgmtAccountSharedServiceRole
  BuildAccountRoleName:
    Type: String
    Default: GAIESBuildAccountCFTRole
Resources:
  BuildAccountCFTRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Ref BuildAccountRoleName
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub >-
                arn:aws:iam::${MgmtAccountId}:role/${MgmtAccountSharedServiceRole}
            Action: 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: CfnStackAssumeRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudformation:CreateStack'
                  - 'cloudformation:UpdateStack'
                  - 'cloudformation:DeleteStack'
                  - 'cloudformation:DescribeStacks'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 's3:CreateBucket'
                  - 's3:DeleteBucket'
                  - 's3:DeleteBucket*'
                  - 's3:PutBucket*'
                Resource: '*'
Outputs:
  BuildAccountRoleArn:
    Value: !GetAtt BuildAccountCFTRole.Arn
