AWSTemplateFormatVersion: 2010-09-09

Parameters:
    VPCName:
      Type: String
      Description: Name your VPC

    CidrBlock:
      Type: String
      MinLength: '9'
      MaxLength: '18'
      Default: 0.0.0.0/0
      AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
      Description: The IP address range that can be used to SSH to the EC2 instances
      ConstraintDescription: Must be a valid IP CIDR range orm x.x.x.x/x

    AppSubnetCIDR:
      Type: String
      MinLength: '9'
      MaxLength: '18'
      Default: 0.0.0.0/0
      AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
      Description: CIDR IP for App Subnet
      ConstraintDescription: Must be a valid IP CIDR range orm x.x.x.x/x

    DatabaseSubnetCIDR:
      Type: String
      MinLength: '9'
      MaxLength: '18'
      Default: 0.0.0.0/0
      AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
      Description: CIDR IP for Database Subnet
      ConstraintDescription: Must be a valid IP CIDR range orm x.x.x.x/x

############################### RESOURCES ##################################

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: !Ref VPCName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
    Properties:
      Tags:
      - Key: Name
        Value: !Sub ${VPCName}-InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

########################## SUBNETS ###############################

  AppSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref AppSubnetCIDR
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
      - Key: Name
        Value: AppSubnet

  DatabaseSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref DatabaseSubnetCIDR
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
      - Key: Name
        Value: DatabaseSubnet

############################## ROUTE TABLES ##################################

  AppRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: App Route Table

  DatabaseRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Database Route Table

##################### ROUTE TABLE ASSOCIATION ################################

  AppRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AppSubnet
      RouteTableId: !Ref AppRouteTable

  DatabaseRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref DatabaseSubnet
      RouteTableId: !Ref DatabaseRouteTable

Outputs:
  VPC:
    Description: Management VPC
    Value: !Ref VPC
    Export:
      Name: !Sub ${AWS::StackName}-VPC

  AppSubnet:
    Description: App Subnet
    Value: !Ref AppSubnet
    Export:
      Name: !Sub ${AWS::StackName}-AppSubnet

  DatabaseSubnet:
    Description: Database Subnet
    Value: !Ref DatabaseSubnet
    Export:
      Name: !Sub ${AWS::StackName}-DatabaseSubnet
