AWSTemplateFormatVersion: 2010-09-09

Parameters:
    VPCName:
      Type: String
      MinLength: '8'
      MaxLength: '50'
      Description: Name your VPC

    CidrBlock:
      Type: String
      MinLength: '9'
      MaxLength: '18'
      Default: 0.0.0.0/0
      AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
      Description: The IP address range that can be used to SSH to the EC2 instances
      ConstraintDescription: Must be a valid IP CIDR range orm x.x.x.x/x

    DMZASubnetCIDR:
      Type: String
      MinLength: '9'
      MaxLength: '18'
      Default: 0.0.0.0/0
      AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
      Description: CIDR IP for DMZ A Subnet
      ConstraintDescription: Must be a valid IP CIDR range orm x.x.x.x/x

    DMZBSubnetCIDR:
      Type: String
      MinLength: '9'
      MaxLength: '18'
      Default: 0.0.0.0/0
      AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
      Description: CIDR IP for DMZ B Subnet
      ConstraintDescription: Must be a valid IP CIDR range orm x.x.x.x/x

    InternalASubnetCIDR:
      Type: String
      MinLength: '9'
      MaxLength: '18'
      Default: 0.0.0.0/0
      AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
      Description: CIDR IP for Internal A Subnet
      ConstraintDescription: Must be a valid IP CIDR range orm x.x.x.x/x

    InternalBSubnetCIDR:
      Type: String
      MinLength: '9'
      MaxLength: '18'
      Default: 0.0.0.0/0
      AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
      Description: CIDR IP for Internal B Subnet
      ConstraintDescription: Must be a valid IP CIDR range orm x.x.x.x/x

########################### RESOURCES #######################################

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: !Ref VPCName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
    Properties:
      Tags:
      - Key: Name
        Value: !Sub ${VPCName}-InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

########################## SUBNETS ###############################

  DMZASubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref DMZASubnetCIDR
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
      - Key: Name
        Value: DMZSubnetA

  DMZBSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref DMZBSubnetCIDR
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      Tags:
      - Key: Name
        Value: DMZSubnetB

  InternalASubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref InternalASubnetCIDR
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
      - Key: Name
        Value: InternalSubnetA

  InternalBSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: !Ref InternalBSubnetCIDR
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      Tags:
      - Key: Name
        Value: InternalSubnetB

############################## ROUTE TABLES ##################################

  DMZARouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: DMZ Route Table A

  DMZBRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: DMZ Route Table B

  InternalARouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Internal Route Table A

  InternalBRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Internal Route Table B

##################### ROUTE TABLE ASSOCIATION ################################

  DMZARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref DMZASubnet
      RouteTableId: !Ref DMZARouteTable

  DMZBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref DMZBSubnet
      RouteTableId: !Ref DMZBRouteTable

  InternalARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref InternalASubnet
      RouteTableId: !Ref InternalARouteTable

  InternalBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref InternalBSubnet
      RouteTableId: !Ref InternalBRouteTable

################################ OUTPUTS #####################################

Outputs:
  VPC:
    Description: Management VPC
    Value: !Ref VPC
    Export:
      Name: !Sub ${AWS::StackName}-VPC

  DMZASubnet:
    Description: DMZ Subnet in AZ a
    Value: !Ref DMZASubnet
    Export:
      Name: !Sub ${AWS::StackName}-DMZASubnet

  DMZBSubnet:
    Description: DMZ Subnet in AZ b
    Value: !Ref DMZBSubnet
    Export:
      Name: !Sub ${AWS::StackName}-DMZBSubnet

  InternalASubnet:
    Description: Internal Subnet in AZ a
    Value: !Ref InternalASubnet
    Export:
      Name: !Sub ${AWS::StackName}-InternalASubnet

  InternalBSubnet:
    Description: Internal Subnet in AZ b
    Value: !Ref InternalBSubnet
    Export:
      Name: !Sub ${AWS::StackName}-InternalBSubnet
