AWSTemplateFormatVersion: 2010-09-09

Parameters:
    VPCName:
      Type: String
      MinLength: '8'
      MaxLength: '50'
      Description: Name your VPC

    CidrBlock:
      Type: String
      MinLength: '9'
      MaxLength: '18'
      Default: 0.0.0.0/0
      AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
      Description: The IP address range that can be used to SSH to the EC2 instances
      ConstraintDescription: Must be a valid IP CIDR range orm x.x.x.x/x

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: !Ref VPCName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
    Properties:
      Tags:
      - Key: Name
        Value: !Sub ${VPCName}-InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

########################## SUBNETS ###############################

  DMZASubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.20.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
      - Key: Name
        Value: DMZSubnetA

  DMZBSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.50.0/24
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      Tags:
      - Key: Name
        Value: DMZSubnetB

  AppASubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.30.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
      - Key: Name
        Value: AppSubnetA

  AppBSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.60.0/24
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      Tags:
      - Key: Name
        Value: AppSubnetB

  DatabaseASubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.40.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
      - Key: Name
        Value: DatabaseSubnetA

  DatabaseBSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.70.0/24
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      Tags:
      - Key: Name
        Value: DatabaseSubnetB

############################## ROUTE TABLES ##################################

  DMZARouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: DMZ Route Table A

  DMZBRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: DMZ Route Table B

  AppARouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: App Route Table A

  AppBRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: App Route Table B

  DatabaseARouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Database Route Table A

  DatabaseBRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Database Route Table B

##################### ROUTE TABLE ASSOCIATION ################################

  DMZARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref DMZASubnet
      RouteTableId: !Ref DMZARouteTable

  DMZBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref DMZBSubnet
      RouteTableId: !Ref DMZBRouteTable

  AppARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AppASubnet
      RouteTableId: !Ref AppARouteTable

  AppBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AppBSubnet
      RouteTableId: !Ref AppBRouteTable

  DatabaseARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref DatabaseASubnet
      RouteTableId: !Ref DatabaseARouteTable

  DatabaseBRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref DatabaseBSubnet
      RouteTableId: !Ref DatabaseBRouteTable

Outputs:
  VPC:
    Description: Management VPC
    Value: !Ref VPC
    Export:
      Name: !Sub ${AWS::StackName}-VPC

  DMZASubnet:
    Description: DMZ Subnet in AZ a
    Value: !Ref DMZASubnet
    Export:
      Name: !Sub ${AWS::StackName}-DMZASubnet

  DMZBSubnet:
    Description: DMZ Subnet in AZ b
    Value: !Ref DMZBSubnet
    Export:
      Name: !Sub ${AWS::StackName}-DMZBSubnet

  AppASubnet:
    Description: App Subnet in AZ a
    Value: !Ref AppASubnet
    Export:
      Name: !Sub ${AWS::StackName}-AppASubnet

  AppBSubnet:
    Description: App Subnet in AZ b
    Value: !Ref AppBSubnet
    Export:
      Name: !Sub ${AWS::StackName}-AppBSubnet

  DatabaseASubnet:
    Description: Database Subnet in AZ a
    Value: !Ref DatabaseASubnet
    Export:
      Name: !Sub ${AWS::StackName}-DatabaseASubnet

  DatabaseBSubnet:
    Description: Database Subnet in AZ b
    Value: !Ref DatabaseBSubnet
    Export:
      Name: !Sub ${AWS::StackName}-DatabaseBSubnet
