AWSTemplateFormatVersion: 2010-09-09

Parameters:
    VPCName:
      Type: String
      MinLength: '8'
      MaxLength: '50'
      Description: Name your VPC

    CidrBlock:
      Type: String
      MinLength: '9'
      MaxLength: '18'
      Default: 0.0.0.0/0
      AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
      Description: The IP address range that can be used to SSH to the EC2 instances
      ConstraintDescription: Must be a valid IP CIDR range orm x.x.x.x/x

Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref CidrBlock
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: !Ref VPCName

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    DependsOn: VPC
    Properties:
      Tags:
      - Key: Name
        Value: !Sub ${VPCName}-InternetGateway

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  TransitASubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.50.0/24
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      Tags:
      - Key: Name
        Value: TransitASubnet

  TransitBSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.1.60.0/24
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      Tags:
      - Key: Name
        Value: TransitBSubnet

  RouteTableA:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Route Table A

  RouteTableB:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Route Table B

  RouteTableAAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref TransitASubnet
      RouteTableId: !Ref RouteTableA

  RouteTableBAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref TransitBSubnet
      RouteTableId: !Ref RouteTableB

Outputs:
  VPC:
    Description: Management VPC
    Value: !Ref VPC
    Export:
      Name: !Sub ${AWS::StackName}-VPC

  TransitASubnet:
    Description: Internal Subnet in AZ a
    Value: !Ref TransitASubnet
    Export:
      Name: !Sub ${AWS::StackName}-TransitASubnet

  TransitBSubnet:
    Description: Internal Subnet in AZ b
    Value: !Ref TransitBSubnet
    Export:
      Name: !Sub ${AWS::StackName}-TransitBSubnet
