AWSTemplateFormatVersion: 2010-09-09

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Env Type & VPC"
        Parameters:
          - EnvType
          - VpcId
      -
        Label:
          default: "Customer HTTP Server Security Group"
        Parameters:
          - CustomerHTTPServerSGIpProtocol
          - CustomerHTTPServerSGFromPort
          - CustomerHTTPServerSGToPort
          - CustomerHTTPServerSGCidrIp
      -
        Label:
          default: "Worker Portal Security Group"
        Parameters:
          - WorkerPortalSGIpProtocol
          - WorkerPortalSGFromPort
          - WorkerPortalSGToPort
          - WorkerPortalSGCidrIp
      -
        Label:
          default: "Customer Portal Security Group"
        Parameters:
          - CustomerPortalSGIpProtocol
          - CustomerPortalSGFromPort
          - CustomerPortalSGToPort
          - CustomerPortalSGCidrIp
      -
        Label:
          default: "Batch Security Group"
        Parameters:
          - BatchSGIpProtocol
          - BatchSGFromPort
          - BatchSGToPort
          - BatchSGCidrIp
      -
        Label:
          default: "SFTP Security Group"
        Parameters:
          - SFTPSGIpProtocol
          - SFTPSGFromPort
          - SFTPSGToPort
          - SFTPSGCidrIp
      -
        Label:
          default: "EnterpriseDB Security Group"
        Parameters:
          - EnterpriseDBSGIpProtocol
          - EnterpriseDBSGFromPort
          - EnterpriseDBSGToPort
          - EnterpriseDBSGCidrIp

    ParameterLabels:
      VpcId:
        default: "Which VPC should this template be deployed to?"

      EnvType:
        default: Select a Environment Type

      CustomerHTTPServerSGIpProtocol:
        default: 'Ip Protocol:'
      CustomerHTTPServerSGFromPort:
        default: 'FromPort:'
      CustomerHTTPServerSGToPort:
        default: 'ToPort:'
      CustomerHTTPServerSGCidrIp:
        default: 'CidrIp:'

      WorkerPortalSGIpProtocol:
        default: 'Ip Protocol:'
      WorkerPortalSGFromPort:
        default: 'FromPort:'
      WorkerPortalSGToPort:
        default: 'ToPort:'
      WorkerPortalSGCidrIp:
        default: 'CidrIp:'

      CustomerPortalSGIpProtocol:
        default: 'Ip Protocol:'
      CustomerPortalSGFromPort:
        default: 'FromPort:'
      CustomerPortalSGToPort:
        default: 'ToPort:'
      CustomerPortalSGCidrIp:
        default: 'CidrIp:'

      BatchSGIpProtocol:
        default: 'Ip Protocol:'
      BatchSGFromPort:
        default: 'FromPort:'
      BatchSGToPort:
        default: 'ToPort:'
      BatchSGCidrIp:
        default: 'CidrIp:'

      SFTPSGIpProtocol:
        default: 'Ip Protocol:'
      SFTPSGFromPort:
        default: 'FromPort:'
      SFTPSGToPort:
        default: 'ToPort:'
      SFTPSGCidrIp:
        default: 'CidrIp:'

      EnterpriseDBSGIpProtocol:
        default: 'Ip Protocol:'
      EnterpriseDBSGFromPort:
        default: 'FromPort:'
      EnterpriseDBSGToPort:
        default: 'ToPort:'
      EnterpriseDBSGCidrIp:
        default: 'CidrIp:'

########################### PARAMETERS ##################################

Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id


  EnvType:
    Type: String
    Default: dev
    AllowedValues: [dev, sit, sit1, prod, pre-prod, uat, trn]



######################## CUSTOMER HTTP SERVER PARAMETERS ############################

  CustomerHTTPServerSGIpProtocol:
    Type: String

  CustomerHTTPServerSGFromPort:
    Type: String

  CustomerHTTPServerSGToPort:
    Type: String

  CustomerHTTPServerSGCidrIp:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'

######################## WORKER PORTAL PARAMETERS ############################

  WorkerPortalSGIpProtocol:
    Type: String

  WorkerPortalSGFromPort:
    Type: String

  WorkerPortalSGToPort:
    Type: String

  WorkerPortalSGCidrIp:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'

########################### CUSTOMER PORTAL PARAMETERS ###############################

  CustomerPortalSGIpProtocol:
    Type: String

  CustomerPortalSGFromPort:
    Type: String

  CustomerPortalSGToPort:
    Type: String

  CustomerPortalSGCidrIp:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'

############################## BATCH PARAMETERS #############################

  BatchSGIpProtocol:
    Type: String

  BatchSGFromPort:
    Type: String

  BatchSGToPort:
    Type: String

  BatchSGCidrIp:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'

######################## SFTP PARAMETERS ############################

  SFTPSGIpProtocol:
    Type: String

  SFTPSGFromPort:
    Type: String

  SFTPSGToPort:
    Type: String

  SFTPSGCidrIp:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'

############################ ENTERPRISEDB PARAMETERS ################################

  EnterpriseDBSGIpProtocol:
    Type: String

  EnterpriseDBSGFromPort:
    Type: String

  EnterpriseDBSGToPort:
    Type: String

  EnterpriseDBSGCidrIp:
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'

########################### RESOURCES ##################################

Resources:

######################## CUSTOMER HTTP SERVER SECURITY GROUP #########################

  CustomerHTTPServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Customer HTTP Server in MarketPlace VPC. By default allows all outbound traffic.
      GroupName: !Join ["_", [!Ref EnvType, marketplace_customerhttpserver_sg]]
      SecurityGroupIngress:
        - IpProtocol: !Ref CustomerHTTPServerSGIpProtocol
          FromPort: !Ref CustomerHTTPServerSGFromPort
          ToPort: !Ref CustomerHTTPServerSGToPort
          CidrIp: !Ref CustomerHTTPServerSGCidrIp
      VpcId: !Ref VpcId
      Tags:
      - Key: Name
        Value: CustomerHTTPServer

########################## WORKER PORTAL SECURITY GROUP #############################

  WorkerPortalSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Worker Portal in MarketPlace VPC. By default allows all outbound traffic.
      GroupName: !Join ["_", [!Ref EnvType, marketplace_workerportal_sg]]
      SecurityGroupIngress:
        - IpProtocol: !Ref WorkerPortalSGIpProtocol
          FromPort: !Ref WorkerPortalSGFromPort
          ToPort: !Ref WorkerPortalSGToPort
          CidrIp: !Ref WorkerPortalSGCidrIp
      VpcId: !Ref VpcId
      Tags:
      - Key: Name
        Value: WorkerPortal

###################### CUSTOMER PORTAL SECURITY GROUP ##########################

  CustomerPortalSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Customer Portal in MarketPlace VPC. By default allows all outbound traffic.
      GroupName: !Join ["_", [!Ref EnvType, marketplace_customerportal_sg]]
      SecurityGroupIngress:
        - IpProtocol: !Ref CustomerPortalSGIpProtocol
          FromPort: !Ref CustomerPortalSGFromPort
          ToPort: !Ref CustomerPortalSGToPort
          CidrIp: !Ref CustomerPortalSGCidrIp
      VpcId: !Ref VpcId
      Tags:
      - Key: Name
        Value: CustomerPortal

########################## BATCH SECURITY GROUP ##############################

  BatchSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for Batch in MarketPlace VPC. By default allows all outbound traffic.
      GroupName: !Join ["_", [!Ref EnvType, marketplace_batch_sg]]
      SecurityGroupIngress:
        - IpProtocol: !Ref BatchSGIpProtocol
          FromPort: !Ref BatchSGFromPort
          ToPort: !Ref BatchSGToPort
          CidrIp: !Ref BatchSGCidrIp
      VpcId: !Ref VpcId
      Tags:
      - Key: Name
        Value: Batch

##################### SFTP SECURITY GROUP ##########################

  SFTPSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for SFTP in MarketPlace VPC. By default allows all outbound traffic.
      GroupName: !Join ["_", [!Ref EnvType, marketplace_sftp_sg]]
      SecurityGroupIngress:
        - IpProtocol: !Ref SFTPSGIpProtocol
          FromPort: !Ref SFTPSGFromPort
          ToPort: !Ref SFTPSGToPort
          CidrIp: !Ref SFTPSGCidrIp
      VpcId: !Ref VpcId
      Tags:
      - Key: Name
        Value: SFTP

########################## ENTERPRISEDB SECURITY GROUP ##############################

  EnterpriseDBSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for EnterpriseDB in MarketPlace VPC. By default allows all outbound traffic.
      GroupName: !Join ["_", [!Ref EnvType, marketplace_enterprisedb_sg]]
      SecurityGroupIngress:
        - IpProtocol: !Ref EnterpriseDBSGIpProtocol
          FromPort: !Ref EnterpriseDBSGFromPort
          ToPort: !Ref EnterpriseDBSGToPort
          CidrIp: !Ref EnterpriseDBSGCidrIp
      VpcId: !Ref VpcId
      Tags:
      - Key: Name
        Value: EnterpriseDB

########################### OUTPUTS ##################################

Outputs:
  CustomerHTTPServerSG:
    Description: Security Group Id for Customer HTTP Server in MarketPlace VPC
    Value: !Ref CustomerHTTPServerSG
    Export:
      Name: !Sub ${AWS::StackName}-CustomerHTTPServer

  WorkerPortalSG:
    Description: Security Group Id for Worker Portal in MarketPlace VPC
    Value: !Ref WorkerPortalSG
    Export:
      Name: !Sub ${AWS::StackName}-WorkerPortal

  CustomerPortalSG:
    Description: Security Group Id for Customer Portal in MarketPlace VPC
    Value: !Ref CustomerPortalSG
    Export:
      Name: !Sub ${AWS::StackName}-CustomerPortal

  BatchSG:
    Description: Security Group Id for Batch in MarketPlace VPC
    Value: !Ref BatchSG
    Export:
      Name: !Sub ${AWS::StackName}-Batch

  SFTPSG:
    Description: Security Group Id for SFTP in MarketPlace VPC
    Value: !Ref SFTPSG
    Export:
      Name: !Sub ${AWS::StackName}-SFTP

  EnterpriseDBSG:
    Description: Security Group Id for EnterpriseDB in MarketPlace VPC
    Value: !Ref EnterpriseDBSG
    Export:
      Name: !Sub ${AWS::StackName}-EnterpriseDB
